version: '3.9'

services:
  postgres:
    container_name: db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
